Connection:
    Domain: https://<subdomain>.atlassian.net/
    Username: <email>
    Password: <Jira API token>


JQL: 
    Query: created >= -365d order by created DESC
    #Query: key=DEV-197
    #Query: project in ("DEV1", "DEV2")
        

# Map field names to additional attributes to extract
Attributes:
      Stage: status.name      
      StatusCategory: status.statusCategory.name    
      Level: priority.name
      Labels: labels
      Components: components.name
      Version: fixVersions.last.name
      VersionRelease: fixVersions.last.releaseDate
      ParentId: parent.key
      ParentName: parent.fields.summary
      ParentType: parent.fields.issuetype.name
      AssigneeName: assignee.displayName
      LinksToOutwardKey: issuelinks.first.outwardIssue.key
      LinksToInwardKey: issuelinks.first.inwardIssue.key
      #Timeoriginalestimate: timeoriginalestimate
      #Environment: customfield_10081.last.value
      #Platform: customfield_10084.last.value    
      Timeoriginalestimate: timeoriginalestimate    
      Timeestimate: timeestimate
      Timespent: timespent
      AggreagateTimeoriginalestimate: aggregatetimeoriginalestimate
      AggreagateTimeestimate: aggregatetimeestimate
      AggreagateTimespent: aggregatetimespent
      Workratio: workratio
