Connection:
    Domain: https://<subdomain>.atlassian.net/
    Username: <email>
    Password: <Jira API token>
#    Consumer Key: consumer_key
#    Private Key: |
#        -----BEGIN RSA PRIVATE KEY-----
#        MIICXQIBAAKBgQDL7BKtMeBJJfafe0enaTZi1IlMyTMxWutaYVZ0LPf4TKvOqEr4
#        Evz2xSSJwEwpA2Zqr686M66HmycynlFq9RFrDx/mQhn5R9ejzQKhsZ09rtoENEqY
#        oPUBYTmITIsfWOXv/SG+fWrBUEDHqqREIzH6XsR6US5JCKZkwF5PpTRnYwIDAQAB
#        AoGBAKZ4sQJ8rglpGX02SdeMF570vKVXtxf6jhl5TveGYmRsSvFpB9Kexa26YMqn
#        lkUBBpHfnB/aYzdHDOfQwMydBbq3oqKCs0vqKkNRC7Ssrs4aTqwzhWKTeB/sfE4e
#        9d8MDt1AnxOdys6LZnqOwMjPgQ0Bf7eW+e7CzhLjVLtbXoxpAkEA8rYzE+c2IJXG
#        ys2V5bmEBuALXxR/DNjHxiNRVIYvqbgHXbXxOMkiAyH7yU+FrjjzbtmM0zz1QGqs
#        rnl9PYPH3wJBANcWNN2VDodQf4msjT317GZsceQveOe5WgB4J7VU1KZNvJqFDRJD
#        VAreH4UoIZD9RtE46ZpvQlBD/5uci+6EIP0CQQDnqC+oV466GzraZs8jrKXvSfiQ
#        j6eUQ3SqERuXaVwkyZl+QCI06vSlqNIBmv0lBQaUTuCy3gPXr/mRrjNze0xRAkBs
#        SWbWRCwrXhDH3JLDpiOdsW1pp6jkaUHxyIydU5c4Hx0cYm4hSrpuOkR+QqUbnRgA
#        pbmeofMt+/4ddyRQMj91AdBXFGD/me5Fp1R0glMPVE/KnSHo5eAL9n9506n6I4V/
#        jtSDHyFMkwkKvjikGgvaXJ5kjwjKweS/XYdwrq6E+sik
#        -----END RSA PRIVATE KEY-----
#    Token: 
#    Token Secret: 23OuWPtOHCpEM0RmA33GOTX85GFvRgZE


JQL: 
    #Query: created >= -30d order by created DESC
    #Query: key=EPM-197
    Query: project in ("DEV EPM", "DEV PWR ID")
        

# Map field names to additional attributes to extract
Attributes:
      Stage: status.name      
      StatusCategory: status.statusCategory.name    
      Level: priority.name
      Labels: labels
      Components: components.name
      Version: fixVersions.last.name
      VersionRelease: fixVersions.last.releaseDate
      ParentId: parent.key
      ParentName: parent.fields.summary
      ParentType: parent.fields.issuetype.name
      Timeoriginalestimate: timeoriginalestimate
      Environment: customfield_10081.last.value
      Platform: customfield_10084.last.value
