Connection:
    Domain: https://<your Jira domain>/ #Open Jira in your browser and see the domain name in the browser link, ie. jira.microsoft.com or microsoft.atlassian.net
    Username: <email> #Use an email you use to access Jira.
    Password: <Jira API token> # is your Jira API Token. The token can be generated at https://id.atlassian.com/manage-profile/security/api-tokens


JQL: 
    Query: created >= -365d order by created DESC
    #Query: key=DEV-197
    #Query: project in ("DEV1", "DEV2")
        

# Map field names to additional attributes to extract
Attributes:
      Stage: status.name      
      StatusCategory: status.statusCategory.name    
      Level: priority.name
      Labels: labels
      Components: components.name
      Version: fixVersions.last.name
      VersionRelease: fixVersions.last.releaseDate
      ParentId: parent.key
      ParentName: parent.fields.summary
      ParentType: parent.fields.issuetype.name
      AssigneeName: assignee.displayName
      LinksToOutwardKey: issuelinks.first.outwardIssue.key
      LinksToInwardKey: issuelinks.first.inwardIssue.key
      #Timeoriginalestimate: timeoriginalestimate
      #Environment: customfield_10081.last.value
      #Platform: customfield_10084.last.value    
      Timeoriginalestimate: timeoriginalestimate    
      Timeestimate: timeestimate
      Timespent: timespent
      AggreagateTimeoriginalestimate: aggregatetimeoriginalestimate
      AggreagateTimeestimate: aggregatetimeestimate
      AggreagateTimespent: aggregatetimespent
      Workratio: workratio
